import React, { useState } from "react";
import Spotify from "spotify-web-api-js";

import { useAuth } from "components/UserContext/UserContext";
import LoginBanner from "components/LoginBanner/LoginBanner";
import { ArtistData, Link } from "types";
import { CassetteTape, CircleCheckBig } from "lucide-react";

interface SavePlaylistProps {
  artistData: ArtistData;
  songs: Link[];
}

const TRACKS_PER_REQUEST = 100;

const chunk = <T,>(items: T[], size: number): T[][] => {
  const chunks: T[][] = [];
  for (let i = 0; i < items.length; i += size) {
    chunks.push(items.slice(i, i + size));
  }
  return chunks;
};

const isUnauthorized = (e: unknown) =>
  typeof e === "object" && e !== null && "status" in e && e.status === 401;

const createdSessionKey = (name: string) => `gigplaylist:created:${name}`;

const PLAYLISTS_PER_PAGE = 50;
const MAX_PLAYLIST_PAGES = 20;

const findExistingPlaylist = async (
  spotify: InstanceType<typeof Spotify>,
  userId: string,
  playlistName: string,
) => {
  for (let page = 0; page < MAX_PLAYLIST_PAGES; page++) {
    const { items, next } = await spotify.getUserPlaylists(userId, {
      limit: PLAYLISTS_PER_PAGE,
      offset: page * PLAYLISTS_PER_PAGE,
    });
    const match = items.find(
      (playlist) =>
        playlist.name === playlistName && playlist.owner.id === userId,
    );
    if (match) return match;
    if (!next) return undefined;
  }
  return undefined;
};

const addTracksInChunks = (
  spotify: InstanceType<typeof Spotify>,
  playlistId: string,
  chunks: string[][],
) =>
  chunks.reduce<Promise<unknown>>(
    (promise, uris) =>
      promise.then(() => spotify.addTracksToPlaylist(playlistId, uris)),
    Promise.resolve(),
  );

const SavePlaylist = ({ artistData: { name }, songs }: SavePlaylistProps) => {
  const [loading, setLoading] = useState(false);
  const [done, setDone] = useState(
    () =>
      typeof window !== "undefined" &&
      sessionStorage.getItem(createdSessionKey(name)) === "true",
  );
  const [error, setError] = useState<string | null>(null);
  const { user, logout } = useAuth();
  const savePlaylist = async () => {
    if (!user) return;
    setLoading(true);
    setError(null);
    try {
      const spotify = new Spotify();
      spotify.setAccessToken(user.accessToken);

      const playlistName = `${name} - GigPlayList`;
      const uriChunks = chunk(
        songs.map((song) => song.uri),
        TRACKS_PER_REQUEST,
      );

      const existingPlaylist = await findExistingPlaylist(
        spotify,
        user.user.id,
        playlistName,
      );

      if (existingPlaylist) {
        await spotify.replaceTracksInPlaylist(
          existingPlaylist.id,
          uriChunks[0] ?? [],
        );
        await addTracksInChunks(
          spotify,
          existingPlaylist.id,
          uriChunks.slice(1),
        );
      } else {
        const playlist = await spotify.createPlaylist(user.user.id, {
          name: playlistName,
          description:
            "Playlist generated by https://gigplaylist.sirlisko.com/",
          public: true,
        });
        await addTracksInChunks(spotify, playlist.id, uriChunks);
      }

      sessionStorage.setItem(createdSessionKey(name), "true");
      setDone(true);
    } catch (e) {
      if (isUnauthorized(e)) {
        logout?.();
      }
      setError("Something went wrong saving your playlist. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="text-center mb-8">
      {error && (
        <p role="alert" className="mb-4 text-sm text-red-300">
          {error}
        </p>
      )}
      {loading ? (
        <p className="m-12 text-lg font-medium flex items-center justify-center">
          <CassetteTape className="mr-1 animate-bounce" /> Generating your
          playlist...
        </p>
      ) : done ? (
        <p className="m-12 text-lg font-medium flex items-center justify-center">
          <CircleCheckBig className="mr-2" /> Playlist saved!
        </p>
      ) : (
        <LoginBanner onCreatePlaylist={savePlaylist} showDesc />
      )}
    </div>
  );
};

export default SavePlaylist;
