import React, { useState } from "react";
import Spotify from "spotify-web-api-js";

import { useAuth } from "components/UserContext/UserContext";
import LoginBanner from "components/LoginBanner/LoginBanner";
import { matchSongs } from "utils/matchSongs";
import { Track, ArtistData } from "types";
import { CassetteTape, CircleCheckBig } from "lucide-react";

interface SavePlaylistProps {
  artistData: ArtistData;
  tracks: Track[];
}

const SavePlaylist = ({
  artistData: { name, tracks: links },
  tracks,
}: SavePlaylistProps) => {
  const [loading, setLoading] = useState(false);
  const [done, setDone] = useState(false);
  const { user } = useAuth();
  if (!links || links.length === 0) {
    return null;
  }
  const songs = matchSongs(tracks, links);
  const createPlaylist = () => {
    if (user) {
      setLoading(true);
      const s = new Spotify();
      s.setAccessToken(user.accessToken);
      s.createPlaylist(user.user.id, {
        name: `${name} - GigPlayList`,
        description: "Playlist generated by https://gigplaylist.sirlisko.com/",
        public: true,
      })
        .then((data) => {
          s.addTracksToPlaylist(data.id, songs);
          setDone(true);
        })
        .finally(() => setLoading(false));
    }
  };

  return (
    <div className="text-center mb-8">
      {loading ? (
        <p className="m-12 text-lg font-medium flex items-center justify-center">
          <CassetteTape className="mr-1 animate-bounce" /> Generating your
          playlist...
        </p>
      ) : done ? (
        <p className="m-12 text-lg font-medium flex items-center justify-center">
          <CircleCheckBig className="mr-2" /> Playlist created!
        </p>
      ) : (
        <LoginBanner onCreatePlaylist={createPlaylist} showDesc />
      )}
    </div>
  );
};

export default SavePlaylist;
